enableGlobalCache: false

packageExtensions:
  '@atls-utils/use-hover@*':
    dependencies:
      react-dom: '18.2.0'
  '@atls-ui-proto/avatar@0.0.10':
    dependencies:
      '@stitches/react': '1.2.8'
  '@atls/config-jest@*':
    dependencies:
      jest: '28'
      typescript: '4.6.4'
  '@atls/webpack-proto-imports-loader@*':
    dependencies:
      webpack: '*'
  '@ory/integrations@*':
    dependencies:
      react: '18.2.0'
      react-dom: '18.2.0'
  '@atls-ui-generators/icons@*':
    peerDependencies:
      glob: '*'
  axios@*:
    dependencies:
      debug: '*'
      supports-color: '*'
  '@atls-ui-parts/link@*':
    dependencies:
      '@emotion/css': '11.9.0'
  '@atls-ui-parts/layout@*':
    dependencies:
      csstype: '*'

yarnPath: .yarn/releases/yarn-remote.cjs
