enableGlobalCache: false

packageExtensions:
  '@atls-utils/use-hover@*':
    dependencies:
      react-dom: '18.2.0'
  '@atls/config-jest@*':
    dependencies:
      jest: '28'
      typescript: '4.6.4'
  '@atls/webpack-proto-imports-loader@*':
    dependencies:
      webpack: '*'
  '@ory/integrations@*':
    dependencies:
      react: '18.2.0'
      react-dom: '18.2.0'
  '@atls-ui-generators/icons@*':
    peerDependencies:
      glob: '*'

yarnPath: .yarn/releases/yarn-remote.cjs
