version: '3.8'

services:
  yarn:
    image: node:18.13
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: yarn

  db:
    image: bitnami/postgresql
    environment:
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=db
      - POSTGRESQL_USER=postgres
    ports:
      - '5432:5432'

  kratos-migrate:
    depends_on:
      - db
    image: docker.io/oryd/kratos:v1.0.0
    environment:
      - DSN=postgres://postgres:password@db:5432/db?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - type: bind
        source: ./config/ory/kratos
        target: /config/kratos
    command: -c /config/kratos/kratos.yaml migrate sql -e --yes
    restart: on-failure
    networks:
      - default

  kratos:
    depends_on:
      - kratos-migrate
      - mailslurper
      - db
    image: oryd/kratos:v1.0.0
    ports:
      - '4433:4433'
      - '4434:4434'
    restart: unless-stopped
    env_file: .env.kratos.stage
    environment:
      - DSN=postgres://postgres:password@db:5432/db?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace
    #УБРАТЬ dev, ТОЛЬКО ДЛЯ ТЕСТИРОВАНИЯ
    command: serve --dev -c /config/kratos/kratos.yaml --dev --watch-courier
    volumes:
      - type: bind
        source: ./config/ory/kratos
        target: /config/kratos

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'

  oathkeeper:
    image: oryd/oathkeeper:v0.40.6
    command: serve --config /config/oathkeeper/oathkeeper.yml
    volumes:
      - type: bind
        source: ./config/ory/oathkeeper
        target: /config/oathkeeper
    ports:
      - '4455:4455'
      - '4456:4456'

  keto:
    image: oryd/keto:v0.11.1
    depends_on:
      - db
      - keto-migrate
    environment:
      - DSN=postgres://postgres:password@db:5432/db?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace
    command: serve -c /config/keto/keto.yaml
    restart: on-failure
    volumes:
      - type: bind
        source: ./config/ory/keto
        target: /config/keto
        read_only: true
      - type: bind
        source: ./shared/keto/src/namespaces
        target: /config/keto/namespaces
    ports:
      - '4466:4466'
      - '4467:4467'

  keto-init:
    image: oryd/keto:v0.11.1
    environment:
      KETO_WRITE_REMOTE: keto:4467
    command: relation-tuple create /config/keto/relation-tuples --insecure-disable-transport-security
    restart: on-failure
    volumes:
      - type: bind
        source: ./config/ory/keto
        target: /config/keto
        read_only: true
      - type: bind
        source: ./shared/keto/src/namespaces
        target: /config/keto/namespaces

  keto-migrate:
    depends_on:
      - db
    image: oryd/keto:v0.11.1
    environment:
      - DSN=postgres://postgres:password@db:5432/db?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - type: bind
        source: ./config/ory/keto
        target: /config/keto
      - type: bind
        source: ./shared/keto/src/namespaces
        target: /config/keto/namespaces
    command: -c /config/keto/keto.yaml migrate up --yes
    restart: on-failure
