version: '3.8'

networks:
  internal:
  garnet:

services:
  yarn:
    image: node:18.13
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: yarn
    networks:
      - internal

  oathkeeper:
    image: oryd/oathkeeper:v0.40.6
    command: serve --config /config/oathkeeper/oathkeeper.yaml
    volumes:
      - ./config/ory/oathkeeper/stage/oathkeeper.yaml:/config/oathkeeper/oathkeeper.yaml
      - ./config/ory/oathkeeper/stage/jwks.json:/config/oathkeeper/jwks.json
      - ./config/ory/oathkeeper/stage/access-rules.yaml:/config/oathkeeper/access-rules.yaml
    ports:
      - '4455:4455'
      - '4456:4456'
    labels:
      - 'traefik.http.routers.oathkeeper-app.entrypoints=websecure'
      - 'traefik.http.routers.oathkeeper-app.rule=Host(`stage.garnet.pet-project.habr.com`)'
      - 'traefik.http.routers.oathkeeper-app.tls=true'
      - 'traefik.http.routers.oathkeeper-app.middlewares=cor'
      - 'traefik.http.middlewares.cor.headers.accesscontrolallowmethods=POST,GET,OPTIONS'
      - 'traefik.http.middlewares.cor.headers.accesscontrolallowheaders=*'
      - 'traefik.http.middlewares.cor.headers.accesscontrolalloworiginlist=*'
      - 'traefik.http.middlewares.cor.headers.accesscontrolmaxage=86400'
      - 'traefik.http.middlewares.cor.headers.addvaryheader=true'
    networks:
      - garnet
      - internal

  identity:
    restart: unless-stopped
    image: node:18.13
    working_dir: /workspace
    entrypoint: bash -c "yarn workspace @identity/renderer-entrypoint prepack ; yarn workspace @identity/renderer-entrypoint start"
    environment:
      - NEXT_PUBLIC_KRATOS_URL=https://stage.garnet.pet-project.habr.com/kratos
      - NEXT_PUBLIC_BACKEND_URL=https://stage.garnet.pet-project.habr.com/api/graphql
    volumes:
      - ./:/workspace
    ports:
      - '3010:3010'
    depends_on:
      - yarn
      - kratos
    networks:
      - internal

  app:
    restart: unless-stopped
    image: node:18.13
    working_dir: /workspace
    volumes:
      - ./:/workspace
    environment:
      - NEXT_PUBLIC_KRATOS_URL=https://stage.garnet.pet-project.habr.com/kratos
      - NEXT_PUBLIC_BACKEND_URL=https://stage.garnet.pet-project.habr.com/api/graphql
    entrypoint: bash -c "yarn workspace @app/renderer-entrypoint prepack ; yarn workspace @app/renderer-entrypoint start"
    ports:
      - '3020:3020'
    depends_on:
      - yarn
    networks:
      - internal

  kratos:
    depends_on:
      kratos-migrate:
        condition: service_completed_successfully
    image: oryd/kratos:v1.0.0
    ports:
      - '4433:4433'
    restart: unless-stopped
    environment:
      - DSN=postgres://postgres:password@garnet-backend-kratos-db:5432/postgres?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace
      - SELFSERVICE_FLOWS_REGISTRATION_AFTER_HOOKS_0_CONFIG_AUTH_CONFIG_VALUE
    command: serve -c /config/kratos/kratos.yaml --dev --watch-courier
    volumes:
      - type: bind
        source: ./config/ory/kratos/stage
        target: /config/kratos
      - type: bind
        source: /etc/ssl/certs
        target: /etc/ssl/certs
    networks:
      - internal

  kratos-migrate:
    image: docker.io/oryd/kratos:v1.0.0
    environment:
      - DSN=postgres://postgres:password@garnet-backend-kratos-db:5432/postgres?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - type: bind
        source: ./config/ory/kratos/stage
        target: /config/kratos
    command: -c /config/kratos/kratos.yaml migrate sql -e --yes
    restart: on-failure
    networks:
      - internal
