version: v1.0.0

dsn: memory

serve:
  public:
    base_url: http://localhost:4433/
    cors:
      enabled: true
      allowed_origins:
        - http://localhost:3000
        - http://identity:3000
        - http://localhost:4455
        - http://oathkeeper:4455
        - http://localhost:4466
        - http://keto:4466
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      allowed_headers:
        - Authorization
        - Cookie
        - Content-Type
        - X-Session-Token
      exposed_headers:
        - Content-Type
        - Set-Cookie
      allow_credentials: true
      debug: true
  admin:
    base_url: http://kratos:4434

session:
  cookie:
    domain: localhost

selfservice:
  default_browser_return_url: http://localhost:3000/app
  allowed_return_urls:
    - http://localhost:3000/
    - http://localhost:4455/

  methods:
    password:
      enabled: true
    link:
      enabled: true
    totp:
      enabled: true
      config:
        issuer: localhost
    lookup_secret:
      enabled: true
    oidc:
      enabled: false

  flows:
    error:
      ui_url: http://localhost:3000/auth/error

    settings:
      ui_url: http://localhost:3000/auth/recovery/new-password
      privileged_session_max_age: 15m
      required_aal: aal1

    recovery:
      enabled: true
      ui_url: http://localhost:3000/auth/recovery
      use: link
      lifespan: 1h

    verification:
      enabled: false

    logout:
      after:
        default_browser_return_url: http://localhost:3000/auth/login

    login:
      ui_url: http://localhost:3000/auth/login

    registration:
      ui_url: http://localhost:3000/auth/registration
      lifespan: 10m
      after:
        default_browser_return_url: http://localhost:3000/auth/confirmation
        hooks:
          - hook: web_hook
            config:
              url: "http://host.docker.internal:3000/api/v1/auth/registration/callback"
              method: POST
              body: file:///config/kratos/user-create.webhook.jsonnet
              auth:
                type: api_key
                config:
                  name: Authorization
                  #ЗАМЕНИТЬ НА РЕАЛЬНЫЙ КЛЮЧ
                  value: GARNET_API_KEY
                  in: header

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE

hashers:
  argon2:
    parallelism: 1
    memory: 128MB
    iterations: 2
    salt_length: 16
    key_length: 16

identity:
  schemas:
    - id: default
      url: file:///config/kratos/identity.schema.json
  default_schema_id: default

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true&legacy_ssl=true
