- id: auth
  upstream:
    url: http://identity:3010/
  match:
    url: https://stage.garnet.pet-project.habr.com/<(?!app).*>
#    url: http://localhost:4455/<(?!app).*>
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    - handler: anonymous
  authorizer:
    handler: allow
  mutators:
    - handler: noop
  errors:
    - handler: json

- id: app
  upstream:
    url: http://app:3020/
  match:
    url: https://stage.garnet.pet-project.habr.com/app<.*>
#    url: http://localhost:4455/app<.*>
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    - handler: cookie_session
  authorizer:
    handler: allow
  mutators:
    - handler: id_token
  errors:
    - handler: redirect
