- id: auth
  upstream:
    url: http://localhost:3000/
  match:
    url: http://<127.0.0.1|localhost>:4455/<(?!app|admin).*>
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    - handler: anonymous
  authorizer:
    handler: allow
  mutators:
    - handler: noop
  errors:
    - handler: json

- id: app
  upstream:
    url: http://localhost:3000/app
  match:
    url: http://<127.0.0.1|localhost>:4455/app<.*>
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    - handler: anonymous
  authorizer:
    handler: allow
  mutators:
    - handler: id_token
  errors:
    - handler: redirect
