name: 📓 Пользовательская история
description: Пользовательская история со сценариями
title: "📓 "
labels:
  - user-story
body:
  - type: markdown
    attributes:
      value: |
        # 📓 Пользовательская история
  - type: textarea
    id: function-scenarios
    attributes:
      label: Пользовательская история и сценарии
      placeholder: |
        Функция: ...
          Я, как пользователь...
          Хочу...
          Чтобы...

        Сценарий: ...
          Допустим ...
          Когда ...
          Тогда ...
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Дополнительная информация
      placeholder: Прочая информация, полезная при реализации функциональности