service: garnet-backend

image: picolino/garnet-backend

env:
  secret:
    - MONGO_CONNSTRING
    - S3_ACCESS_KEY
    - S3_SECRET_KEY
    - GARNET_API_KEY
  clear:
    - S3_BUCKET
    - S3_ENDPOINT

registry:
  server: ghcr.io
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD

healthcheck:
  path: /api/v1/up

accessories:
  db:
    image: mongo:6
    port: 27017
    env:
      clear:
        MONGO_INITDB_ROOT_USERNAME: garnet
      secret:
        - MONGO_INITDB_ROOT_PASSWORD
    directories:
      - data:/data/db

traefik:
  options:
    publish:
      - "443:443"
    volume:
      - traefik:/configuration
  labels:
    traefik.http.routers.garnet-backend-websecure-stage.entrypoints: websecure
    traefik.http.routers.garnet-backend-websecure-stage.tls: true
    traefik.http.routers.garnet-backend-websecure-prod.entrypoints: websecure
    traefik.http.routers.garnet-backend-websecure-prod.tls: true
  args:
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    providers.file.directory: "/configuration/"
    providers.file.watch: true