servers:
  web:
    hosts:
      - 188.225.36.16

accessories:
  db:
    host: 188.225.36.16

traefik:
  labels:
    traefik.http.routers.garnet-backend-websecure-prod.rule: Host(`garnet.pet-project.habr.com`) && PathPrefix(`/api`)
    traefik.http.routers.garnet-backend-websecure-prod.entrypoints: websecure
    traefik.http.routers.garnet-backend-websecure-prod.tls: true
