serve:
  proxy:
    cors:
      enabled: true
      allowed_origins:
      - http://localhost:3010
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - '*'
      exposed_headers:
        - '*'
      allow_credentials: true
      debug: true

access_rules:
  repositories:
    - file:///config/oathkeeper/access-rules.yaml
  matching_strategy: regexp

authenticators:
  anonymous:
    enabled: true
    config:
      subject: guest

  cookie_session:
    enabled: true
    config:
      check_session_url: http://kratos:4433/sessions/whoami
      preserve_path: true
      extra_from: '@this'
      subject_from: 'identity.id'
      only:
        - ory_kratos_session
  noop:
    enabled: true

authorizers:
  allow:
    enabled: true
  remote_json:
    enabled: true
    config:
      remote: http://keto:4466/check
      forward_response_headers_to_upstream: []
      payload: |
        {
          "subject": "{{ print .Subject }}",
          "resource": "{{ printIndex .MatchContext.RegexpCaptureGroups 0 }}"
        }
  deny:
    enabled: true

mutators:
  noop:
    enabled: true
  id_token:
    enabled: true
    config:
      jwks_url: file:///config/oathkeeper/jwks.json
      issuer_url: http://oathkeeper:4455
      ttl: 1h
      claims: |
        {
          "session": {{ .Extra | toJson }}
        }
  header:
    enabled: true
    config:
      headers:
        X-Oathkeeper: oathkeeper

errors:
  fallback:
    - json
  handlers:
    redirect:
      enabled: true
      config:
        to: http://localhost:4455/auth/login
        when:
          - error:
              - unauthorized
              - forbidden
            request:
              header:
                accept:
                  - text/html
    json:
      enabled: true
      config:
        verbose: true

log:
  level: debug
  format: text
  leak_sensitive_values: true
