using Garnet.Projects.Infrastructure.Api.ProjectTeamJoinRequest;

namespace Garnet.Projects.Infrastructure.Api.ProjectTeamJoinRequestGet;

public record ProjectTeamJoinRequestGetPayload(ProjectTeamJoinRequestPayload[] ProjectTeamJoinRequest);