name: Backend Check-In

env:
  NET_VERSION: '6.0.300'
  GITHUB_API_KEY: ${{ github.token }}

on: [pull_request]

jobs:
  check_in:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.NET_VERSION }}

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutput=coverage/lcov.info /p:CoverletOutputFormat=lcov
