name: Backend Build and Deploy to Prod

on:
  push:
    tags:
      - 'v*'
      
jobs:
  build_and_deploy:
    uses: habralab/garnet-team/.github/workflows/backend-deploy.yml@master
    with:
      deployment_target: prod
      deployment_target_url: https://garnet.pet-project.habr.com/
    secrets: inherit